name: coecms

channels:
    - coecms
    - conda-forge
    - defaults

dependencies:
    - python
    - pytest
    - sphinx
    - cdo
    - mule
    - cfunits
    - dask
    - esmf # Only for testing on desktops/circleci - production gets it from /apps/esmf
    - xarray
    - netcdf4
    - sparse
